//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "countries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i16,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub phone_code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cities::Entity")]
    Cities,
    #[sea_orm(has_many = "super::phone_numbers::Entity")]
    PhoneNumbers,
}

impl Related<super::cities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cities.def()
    }
}

impl Related<super::phone_numbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhoneNumbers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
