//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "phone_numbers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "unique_phone_per_country")]
    pub value: String,
    #[sea_orm(unique_key = "unique_phone_per_country")]
    pub country_id: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryId",
        to = "super::countries::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Countries,
    #[sea_orm(has_many = "super::user_phone_numbers::Entity")]
    UserPhoneNumbers,
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Countries.def()
    }
}

impl Related<super::user_phone_numbers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPhoneNumbers.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_phone_numbers::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::user_phone_numbers::Relation::PhoneNumbers
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
