//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::cities::Entity as Cities;
pub use super::countries::Entity as Countries;
pub use super::phone_numbers::Entity as PhoneNumbers;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::roles::Entity as Roles;
pub use super::user_phone_numbers::Entity as UserPhoneNumbers;
pub use super::users::Entity as Users;
